# Generated by Django 4.0 on 2022-03-15 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='applicationfees',
            field=models.CharField(max_length=18),
        ),
        migrations.AlterField(
            model_name='app',
            name='deadline',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='app',
            name='eligibilitycriteria',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='app',
            name='exam',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='app',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='app',
            name='providedby',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='app',
            name='scholarshipamount',
            field=models.CharField(max_length=18),
        ),
    ]
