# Generated by Django 4.0.2 on 2022-03-17 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_app_applicationfees_alter_app_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='applicationfees',
            field=models.CharField(max_length=18, verbose_name='Application Fees'),
        ),
        migrations.AlterField(
            model_name='app',
            name='eligibilitycriteria',
            field=models.CharField(help_text='Enter Eligibility Criteria', max_length=512, verbose_name='Eligibility Criteria'),
        ),
        migrations.AlterField(
            model_name='app',
            name='exam',
            field=models.CharField(help_text='Enter if any exam is required', max_length=64),
        ),
        migrations.AlterField(
            model_name='app',
            name='link',
            field=models.CharField(help_text='Enter 404 if not available', max_length=128),
        ),
        migrations.AlterField(
            model_name='app',
            name='name',
            field=models.CharField(help_text='Enter Name of Scholarship', max_length=64),
        ),
        migrations.AlterField(
            model_name='app',
            name='providedby',
            field=models.CharField(help_text='Enter name of sponsor or organization', max_length=64, verbose_name='Provided By'),
        ),
        migrations.AlterField(
            model_name='app',
            name='scholarshipamount',
            field=models.CharField(max_length=18, verbose_name='Scholarship Amount'),
        ),
    ]
