# Generated by Django 4.0 on 2022-03-24 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_app_applicationfees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='category',
            field=models.CharField(blank=True, choices=[('National', 'NATIONAL'), ('International', 'INTERNATIONAL')], max_length=200, null=True, verbose_name='Category'),
        ),
    ]
