# Generated by Django 4.0 on 2022-03-25 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_app_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='levels',
            field=models.CharField(blank=True, choices=[('Undergraduate', 'UNDERGRADUATE'), ('Postgraduate', 'POSTGRADUATE'), ('Phd', 'PhD')], max_length=200, null=True, verbose_name='Levels'),
        ),
    ]
