# Generated by Django 4.0 on 2022-03-26 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_app_salaries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='salaries',
        ),
    ]
